package com.cashflow.entity;

import jakarta.persistence.*;
import java.time.Instant;
import java.util.UUID;

/**
 * Represents a participant in the cash-flow settlement system.
 *
 * <p>Kept deliberately lean: the settlement algorithm only cares about a
 * stable UUID identity. Everything else (email, profile picture, OAuth tokens)
 * belongs in a separate user-management service -- we do not want this
 * financial-core module to grow into a monolith.</p>
 *
 * <p><b>Primary key:</b> UUID generated by the DB (strategy = UUID)
 * rather than a sequential long -- this lets rows be created off-database
 * (e.g. in a future microservice split) without coordination.</p>
 */
@Entity
@Table(
    name = "users",
    indexes = {
        // Unique index so we can look up by username in O(log N) without
        // a full table scan -- important for the ingestion validation path.
        @Index(name = "idx_user_username", columnList = "username", unique = true)
    }
)
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "uuid")
    private UUID id;

    /**
     * Unique human-readable handle (e.g. "alice", "bob").
     * Not an email -- we are not building auth here.
     */
    @Column(name = "username", nullable = false, unique = true, length = 64)
    private String username;

    /**
     * Display name shown in settlement summaries (e.g. "Alice Wonderland").
     * Needed for readable console output in Phase 4 TestRunner.
     */
    @Column(name = "display_name", nullable = false, length = 128)
    private String displayName;

    /** When this user record was first created. Immutable after insert. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @PrePersist
    protected void onCreate() {
        this.createdAt = Instant.now();
    }

    /** Required by JPA. */
    protected User() {}

    /**
     * Application-level constructor -- used by the service layer and TestRunner.
     *
     * @param username    unique handle; must not be null
     * @param displayName human-readable name for settlement output
     */
    public User(String username, String displayName) {
        this.username    = username;
        this.displayName = displayName;
    }

    public UUID    getId()                  { return id; }
    public String  getUsername()            { return username; }
    public void    setUsername(String u)    { this.username = u; }
    public String  getDisplayName()         { return displayName; }
    public void    setDisplayName(String d) { this.displayName = d; }
    public Instant getCreatedAt()           { return createdAt; }

    @Override
    public String toString() {
        return "User{id=" + id + ", username='" + username + "', displayName='" + displayName + "'}";
    }
}
